[package]
name = "tree-cli"
version = "0.1.0"
authors = ["edifierx666 <edifierx666@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="*"

